# Generated by Django 4.2.4 on 2023-09-13 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='image_url',
            field=models.URLField(default='https://norecipes.com/wp-content/uploads/2012/07/california-roll-012.jpg'),
        ),
    ]
